# Generated by Django 3.1.7 on 2021-03-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lname',
        ),
    ]
